=== nvaccess/addon-datastore/validation/_validate/addonVersion_schema.json
{
	"examples": [
		{
			"addonId": "easyAddonTech.XYZ",
			"addonVersionNumber": {
				"major": 21,
				"minor": 6,
				"patch": 0
			},
			"addonVersionName": "21.6.0",
			"displayName": "My addon",
			"publisher": "easyAddonTech",
			"description": "Makes doing XYZ easier",
			"homepage": "https://github.com/nvaccess/addon-datastore",
			"minNVDAVersion": {
				"major": 2019,
				"minor": 3,
				"patch": 0
			},
			"lastTestedVersion": {
				"major": 2020,
				"minor": 4,
				"patch": 0
			},
			"channel": "beta",
			"URL": "https://github.com/nvaccess/addon-datastore/releases/download/v0.1.0/myAddon.nvda-addon",
			"sha256": "69D84CA8899800A5575CE31798293CD4FEBAB1D734A07C2E51E56A28E0DF8C82",
			"sourceURL": "https://github.com/nvaccess/addon-datastore/",
			"license": "GPL v2",
			"licenseURL": "https://github.com/nvaccess/addon-datastore/license.MD",
			"changelog": "New features",
			"translations": [
				{
					"language": "de",
					"displayName": "Mein Addon",
					"description": "erleichtert das Durchführen von xyz",
					"changelog": "Neue Funktionen"
				}
			],
			"reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/1942#discussioncomment-7453248",
			"submissionTime": 1723523492363
		}
	],
	"title": "Root",
	"type": "object",
	"description": "Information about an addon release",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"required": [
		"addonId",
		"addonVersionNumber",
		"addonVersionName",
		"displayName",
		"publisher",
		"description",
		"minNVDAVersion",
		"lastTestedVersion",
		"channel",
		"URL",
		"sha256",
		"sourceURL",
		"license",
		"translations"
	],
	"properties": {
		"addonId": {
			"default": "",
			"description": "The ID for the addon, matches the name field in the addon manifest and the folder name for the submission.",
			"examples": [
				"easyAddonTech.XYZ"
			],
			"title": "The ID for the addon",
			"type": "string"
		},
		"addonVersionNumber": {
			"$ref": "#/$defs/canonicalVersion",
			"title": "The addon version number",
			"description": "Pure numerical representation of the version being released.",
			"default": {},
			"type": "object",
			"examples": [
				{
					"major": 21,
					"minor": 6,
					"patch": 0
				}
			]
		},
		"addonVersionName": {
			"title": "The addon version name",
			"description": "The addon version being released. Must match the version in the addon manifest and the file name for the submission.",
			"type": "string",
			"default": "",
			"examples": [
				"21.6.0",
				"21.6",
				"21.06"
			]
		},
		"displayName": {
			"default": "",
			"description": "The name that will be displayed in English for the addon.",
			"examples": [
				"My addon"
			],
			"title": "The display name (en) of the addon",
			"type": "string"
		},
		"publisher": {
			"default": "",
			"description": "The name of the individual, group, or company responsible for the addon.",
			"examples": [
				"NV Access"
			],
			"title": "The publisher name for the addon",
			"type": "string"
		},
		"description": {
			"default": "",
			"description": "The English description of the addon that will be displayed for the addon.",
			"examples": [
				"Makes doing XYZ easier"
			],
			"title": "The description (en) of the addon",
			"type": "string"
		},
		"homepage": {
			"default": "",
			"description": "If the addon has a homepage where users can get more information about the addon, you can specify it here.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore"
			],
			"pattern": "^https:.*",
			"title": "The homepage URL for the addon.",
			"type": "string"
		},
		"minNVDAVersion": {
			"$ref": "#/$defs/canonicalVersion",
			"default": {},
			"title": "The minNVDAVersion schema",
			"description": "The addon will not work with versions of NVDA prior to this version.",
			"examples": [
				{
					"major": 2019,
					"minor": 3,
					"patch": 0
				}
			]
		},
		"lastTestedVersion": {
			"$ref": "#/$defs/canonicalVersion",
			"title": "The lastTestedVersion schema",
			"description": "The add-on has been tested up to and including this version of NVDA",
			"default": {},
			"examples": [
				{
					"major": 2020,
					"minor": 4,
					"patch": 0
				}
			]
		},
		"channel": {
			"default": "",
			"description": "Used to define pre-release (beta) add-ons. Should be either 'stable', 'beta' or 'dev'",
			"examples": [
				"beta"
			],
			"title": "The channel for the addon",
			"enum": [
				"stable",
				"beta",
				"dev"
			],
			"type": "string"
		},
		"URL": {
			"default": "",
			"description": "To allow directly downloading the *.nvda-addon file. The URL should remain valid indefinitely. GitHub release URLs are recommended.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/releases/download/v0.1.0/myAddon.nvda-addon"
			],
			"title": "The URL to download the add-on.",
			"type": "string"
		},
		"sha256": {
			"default": "",
			"description": "Use the python script '_tools/genSha256.py' to generate this value.",
			"examples": [
				"69D84CA8899800A5575CE31798293CD4FEBAB1D734A07C2E51E56A28E0DF8C82"
			],
			"title": "The sha256 for the *.nvda-addon file.",
			"type": "string"
		},
		"sourceURL": {
			"default": "",
			"description": "Allows reviewers to inspect the source code for common issues.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/"
			],
			"title": "The URL for the add-on source",
			"type": "string"
		},
		"license": {
			"default": "",
			"description": "The short name of the license.",
			"examples": [
				"GPL v2"
			],
			"title": "The short name of the license for the addon",
			"type": "string"
		},
		"licenseURL": {
			"default": "",
			"description": "A URL to the full license for the addon.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/license.MD"
			],
			"title": "The URL of the license",
			"type": "string"
		},
		"changelog": {
			"default": "",
			"description": "Changes between the previous and the current version",
			"examples": [
				"New feature"
			],
			"title": "Add-on changelog (en)",
			"type": "string"
		},
		"legacy": {
			"default": false,
			"description": "Legacy add-ons have invalid data or manifest. Legacy add-ons are not listed in the NVDA add-on store.",
			"examples": [
				true
			],
			"title": "Mark add-on as legacy",
			"type": "boolean"
		},
		"translations": {
			"default": [],
			"description": "A collection of translations generated from localized add-on manifests",
			"examples": [
				[
					{
						"language": "de",
						"displayName": "Mein Addon",
						"description": "erleichtert das Durchführen von xyz",
						"changelog": "Neue Funktionen"
					}
				]
			],
			"title": "Translations",
			"type": "array",
			"items": {
				"$ref": "#/$defs/translation"
			}
		},
		"reviewUrl": {
			"default": "",
			"description": "A URL to the discussion comment to review the add-on version.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/discussions/1942#discussioncomment-7453248"
			],
			"title": "Discussion comment URL",
			"type": "string"
		},
		"submissionTime": {
			"default": 0,
			"description": "Timestamp in milliseconds, corresponding to the submission time of the add-on",
			"examples": [
				1723523492363
			],
			"title": "Submission time",
			"type": "number"
		},
		"vtScanUrl": {
			"default": "",
			"description": "A URL to the Virus Total scan for the add-on version.",
			"examples": [
				"https://www.virustotal.com/gui/file/3fda88d598e9747b2dfadfdfb8930a737c0049e9782392bffcd59ef668821547"
			],
			"title": "VirusTotal scan URL",
			"type": "string"
		},
		"scanResults": {
			"default": {},
		"description": "Results from VirusTotal scanning.",
			"examples": [
				{
					"virusTotal": {}
				}
			],
			"title": "Scan results",
			"type": "object"
		}
	},
	"$defs": {
		"canonicalVersion": {
			"default": {},
			"type": "object",
			"examples": [
				{
					"major": 21,
					"minor": 6,
					"patch": 0
				}
			],
			"required": [
				"major",
				"minor",
				"patch"
			],
			"properties": {
				"major": {
					"default": 0,
					"description": "'major' in major.minor.patch",
					"examples": [
						21,
						2019,
						2021
					],
					"title": "The 'major' part of the version number.",
					"type": "integer"
				},
				"minor": {
					"default": 0,
					"description": "The 'minor' part in major.minor.patch",
					"examples": [
						3
					],
					"title": "The 'minor' part of the version number.",
					"type": "integer"
				},
				"patch": {
					"default": 0,
					"description": "The 'patch' part in major.minor.patch",
					"examples": [
						0
					],
					"title": "The 'patch' part of the version number.",
					"type": "integer"
				}
			}
		},
		"translation": {
			"default": {},
			"type": "object",
			"examples": [
				{
					"language": "de",
					"displayName": "Mein Addon",
					"description": "erleichtert das Durchführen von xyz",
					"changelog": "Neue Funktionen"
				}
			],
			"required": [
				"language",
				"displayName",
				"description"
			],
			"properties": {
				"language": {
					"default": "",
					"description": "Language code supported by NVDA",
					"examples": [
						"de",
						"pt_BR"
					],
					"title": "Language code",
					"type": "string"
				},
				"displayName": {
					"default": "",
					"description": "The translated name that will be displayed for the addon.",
					"examples": [
						"Mein Addon"
					],
					"title": "Translated display name",
					"type": "string"
				},
				"description": {
					"default": "",
					"description": "Translated description that will be displayed for the addon.",
					"examples": [
						"erleichtert das Durchführen von xyz"
					],
					"title": "The translated description",
					"type": "string"
				},
				"changelog": {
					"default": "",
					"description": "Translated description of changes between the previous and this add-on version",
					"examples": [
						"Neue Funktionen"
					],
					"title": "The translated changelog",
					"type": "string"
				}
			}
		}
	}
}

=== nvaccess/addon-datastore/addons/InternetUsageMonitor/2.1.1.json
{
	"addonId": "InternetUsageMonitor",
	"displayName": "InternetUsageMonitor",
	"URL": "https://github.com/rayo-alcantar/InternetUsageMonitor/releases/download/2.1.1/InternetUsageMonitor-2.1.1.nvda-addon",
	"description": "Complemento para NVDA que monitorea el uso de internet.",
	"sha256": "5dd4b730565001b2f44efaf0857868e5c053a855813ddc375d10315e0bb831a8",
	"addonVersionName": "2.1.1",
	"addonVersionNumber": {
		"major": 2,
		"minor": 1,
		"patch": 1
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Angel Alc\u00e1ntar",
	"sourceURL": "https://github.com/rayo-alcantar/InternetUsageMonitor",
	"license": "GPL v2",
	"homepage": "https://github.com/rayo-alcantar/InternetUsageMonitor/",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": [
		{
			"language": "en",
			"displayName": "InternetUsageMonitor",
			"description": "This addon for NVDA allows you to monitor internet usage."
		},
		{
			"language": "ru",
			"displayName": "\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442-\u043c\u043e\u043d\u0438\u0442\u043e\u0440",
			"description": "\u042d\u0442\u043e \u0434\u043e\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u043f\u043e\u0437\u0432\u043e\u043b\u044f\u0435\u0442 \u043e\u0442\u0441\u043b\u0435\u0436\u0438\u0432\u0430\u0442\u044c \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0435 \u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442\u0430."
		},
		{
			"language": "uk",
			"displayName": "InternetUsageMonitor",
			"description": "\u0414\u043e\u0434\u0430\u0442\u043e\u043a \u0434\u043b\u044f NVDA, \u044f\u043a\u0438\u0439 \u0432\u0456\u0434\u0441\u0442\u0435\u0436\u0443\u0454 \u0432\u0438\u043a\u043e\u0440\u0438\u0441\u0442\u0430\u043d\u043d\u044f \u0406\u043d\u0442\u0435\u0440\u043d\u0435\u0442\u0443."
		}
	]
}

=== nvaccess/addon-datastore/addons/tiflotecniaVoices/4.1.1.json
{
	"addonId": "tiflotecniaVoices",
	"displayName": "Tiflotecnia voices for NVDA",
	"URL": "https://github.com/ruifontes/tiflotecniaVoices/releases/download/4.1.1/tiflotecniaVoices-4.1.1.nvda-addon",
	"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices.",
	"sha256": "fd0a68c69ecc2d440d4caf8a5f1015dcef62bbe3f0d42fb0fb473ad61dfdd4aa",
	"addonVersionName": "4.1.1",
	"addonVersionNumber": {
		"major": 4,
		"minor": 1,
		"patch": 1
	},
	"minNVDAVersion": {
		"major": 2023,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "ruifontes",
	"sourceURL": "https://github.com/ruifontes/tiflotecniaVoices",
	"license": "GPL v2",
	"homepage": "https://www.tiflotecnia.com",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1749925143000,
	"translations": [
		{
			"language": "de",
			"displayName": "Tiflotecnia-Stimmen für NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "es",
			"displayName": "Voces de tiflotecnia para NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "he",
			"displayName": "קולות Tiflotecnia עבור NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "hr",
			"displayName": "Tiflotecnia voices for NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "it",
			"displayName": "Voci di Tiflotecnia per NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "ja",
			"displayName": "Tiflotecnia voices for NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "pl",
			"displayName": "Głosy Tiflotecnia dla NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "pt",
			"displayName": "Vozes Tiflotecnia para o NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "ru",
			"displayName": "Голоса Tiflotecnia для NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "tr",
			"displayName": "NVDA için Tiflotecnia sesleri",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "zh_CN",
			"displayName": "NVDA 的 Tiflotecnia 语音",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		}
	],
	"reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/5322",
	"vtScanUrl": "https://www.virustotal.com/gui/file/fd0a68c69ecc2d440d4caf8a5f1015dcef62bbe3f0d42fb0fb473ad61dfdd4aa"
}

=== nvaccess/addon-datastore/addons/freeradio/2026.20.6.json
{
	"addonId": "freeradio",
	"displayName": "freeRadio",
	"URL": "https://github.com/Surveyor123/freeradio/releases/download/v2026.20.6/freeradio-2026.20.6.nvda-addon",
	"description": "FreeRadio is an internet radio add-on for NVDA that provides seamless access to thousands of stations via the Radio Browser open directory. It features a fully accessible station browser with search, country filter, favourites management, and per-station audio profiles. Playback is handled by a prioritised backend chain (BASS, VLC, PotPlayer, Windows Media Player) with support for volume control, audio effects, output device selection, and simultaneous audio mirroring to a second device. Additional features include instant and scheduled recording, sleep and alarm timers, automatic ICY metadata announcements, Shazam-based music recognition, and a liked-songs log. All controls and shortcuts are designed for NVDA accessibility.",
	"sha256": "68971ed8c9ddf662b50e3f07687a0ff37634e860f5fd43f45d21d48d51b24657",
	"addonVersionName": "2026.20.6",
	"addonVersionNumber": {
		"major": 2026,
		"minor": 20,
		"patch": 6
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 1
	},
	"channel": "stable",
	"publisher": "Çağrı Doğan <cagrid@hotmail.com>",
	"sourceURL": "https://github.com/Surveyor123/freeradio",
	"license": "GPL v2",
	"homepage": "https://github.com/Surveyor123/freeradio",
	"changelog": "\n### New Features\n\n- **Time-shift buffer**: Rewind and fast-forward live radio like a DVR, using a rolling ~10-minute buffer. Enable it from Settings or toggle it instantly with `Ctrl+Win+T`. Rewind 15 seconds with `Ctrl+Win+J`; fast-forward 15 seconds with `Ctrl+Win+K` — reaching the live edge automatically returns you to normal live playback.\n- Time-shift now supports **HLS (`.m3u8`) stations** in addition to plain HTTP/HTTPS and Shoutcast/Icecast (ICY) streams — segments are downloaded and reassembled into the same rewindable buffer.\n\n### Fixes\n\n- Fixed time-shift capture (and recording) failing with an SSL certificate error on stations whose server presents an expired or otherwise invalid TLS certificate.\n\n### Documentation\n\n- Added a full \"Time-Shift (Rewind Live Radio)\" section to the README, plus new shortcut and settings table entries.\n",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1783777135000,
	"translations": []
}

=== nvaccess/addon-datastore/addons/programRAMReporter/1.0.0.json
{
	"addonId": "programRAMReporter",
	"displayName": "Program RAM Usage Reporter",
	"URL": "https://github.com/Ninjacoder42/programRAMReporter/releases/download/%23RAMUsageReporter/programRAMReporter.nvda-addon",
	"description": "This add-on allows you to check the RAM usage of your currently focused program.\nPress NVDA+Shift+9 to hear the current program's memory usage.",
	"sha256": "5961a2c8d16e697f6dbfbefd13ee65583ea5781a6bc30eb7527447a286d0263d",
	"addonVersionName": "1.0.0",
	"addonVersionNumber": {
		"major": 1,
		"minor": 0,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2019,
		"minor": 3,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"channel": "dev",
	"publisher": "Justin",
	"sourceURL": "https://github.com/Ninjacoder42/programRAMReporter",
	"license": "GPL v2",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1729889259000,
	"translations": []
}

=== nvaccess/addon-datastore/addons/showSelectionWhenBrailleTetheredToReview/2024.914.0.json
{
	"addonId": "showSelectionWhenBrailleTetheredToReview",
	"displayName": "Show selection when braille is tethered to review",
	"URL": "https://github.com/burmancomp/show-selection-when-braille-tethered-to-review/releases/download/v2024.0914.0/showSelectionWhenBrailleTetheredToReview-2024.0914.0.nvda-addon",
	"description": "This is a beta version, and there may be issues.\nThere are likely very few testers which means that more or less use cases are\nnot tested. One such case is using braille input.\nIt Shows selection with dots 7 and 8 in edit controls and documents when\nbraille is tethered to review.",
	"sha256": "e040f018df16f211493c689ad24f075418362f39f884967fbecb08789a0d3c08",
	"addonVersionName": "2024.0914.0",
	"addonVersionNumber": {
		"major": 2024,
		"minor": 914,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 2,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 0
	},
	"channel": "beta",
	"publisher": "Burman's Computer And Education Ltd.",
	"sourceURL": "https://github.com/burmancomp/show-selection-when-braille-tethered-to-review/",
	"license": "GPL v2",
	"homepage": "https://github.com/burmancomp/show-selection-when-braille-tethered-to-review",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": [],
	"reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/3762"
}

=== nvaccess/addon-datastore/addons/xPlorer/2026.3.0.json
{
	"addonId": "xPlorer",
	"displayName": "xPlorer",
	"URL": "https://github.com/chaichaimee/xPlorer/releases/download/2026.3-beta/xPlorer-v2026.3-beta.nvda-addon",
	"description": "Improve access to File Explorer.\nHot Keys:\nNVDA+Shift+X : Open xPlorer Context Menu\nNVDA+Shift+z Single Tap : Say Size\nNVDA+Shift+Z Double Tap : Compress Zip\nNVDA+Shift+C Single Tap : Copy Selected File and Folder Names\nNVDA+Shift+C Double Tap : Copy Address Bar Current Folder\nNVDA+Shift+V Single Tap : Copy Content\nNVDA+Shift+V Double Tap : Invert Selection\nNVDA+Shift+F2 : Rename File Only",
	"sha256": "277f61b36b9cb7ea8680afa7a9fe0c899e4aa93323831aa462467ec381d55114",
	"addonVersionName": "2026.3",
	"addonVersionNumber": {
		"major": 2026,
		"minor": 3,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2022,
		"minor": 4,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "chaichaimee",
	"sourceURL": "https://github.com/chaichaimee/xPlorer",
	"license": "GPL v2",
	"homepage": "https://github.com/chaichaimee/xPlorer",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1771046796000,
	"translations": [
		{
			"language": "de",
			"displayName": "xPlorer",
			"description": "Verbesserter Zugriff auf den Datei-Explorer.\nTastenkombinationen:\nNVDA+Shift+X : xPlorer-Kontextmenü öffnen\nNVDA+Shift+Z Einmal drücken : Größe ansagen\nNVDA+Shift+Z Zweimal drücken : Als ZIP komprimieren\nNVDA+Shift+C Einmal drücken : Namen der ausgewählten Dateien und Ordner kopieren\nNVDA+Shift+C Zweimal drücken : Pfad der Adressleiste des aktuellen Ordners kopieren\nNVDA+Shift+V Einmal drücken : Inhalt kopieren\nNVDA+Shift+V Zweimal drücken : Auswahl umkehren\nNVDA+Shift+F2 : Nur Datei umbenennen"
		},
		{
			"language": "en",
			"displayName": "xPlorer",
			"description": "Improve access to File Explorer.\nHot Keys:\nNVDA+Shift+X : Open xPlorer Context Menu\nNVDA+Shift+z Single Tap : Say Size\nNVDA+Shift+Z Double Tap : Compress Zip\nNVDA+Shift+C Single Tap : Copy Selected File and Folder Names\nNVDA+Shift+C Double Tap : Copy Address Bar Current Folder\nNVDA+Shift+V Single Tap : Copy Content\nNVDA+Shift+V Double Tap : Invert Selection\nNVDA+Shift+F2 : Rename File Only"
		},
		{
			"language": "es",
			"displayName": "xPlorer",
			"description": "Mejora el acceso al Explorador de archivos.\nTeclas rápidas:\nNVDA+Shift+X : Abrir el menú contextual de xPlorer\nNVDA+Shift+Z Un toque : Decir tamaño\nNVDA+Shift+Z Dos toques : Comprimir en Zip\nNVDA+Shift+C Un toque : Copiar nombres de archivos y carpetas seleccionados\nNVDA+Shift+C Dos toques : Copiar la barra de direcciones de la carpeta actual\nNVDA+Shift+V Un toque : Copiar contenido\nNVDA+Shift+V Dos toques : Invertir selección\nNVDA+Shift+F2 : Renombrar solo archivo"
		},
		{
			"language": "fr",
			"displayName": "xPlorer",
			"description": "Améliore l'accès à l'Explorateur de fichiers.\nTouches de raccourci :\nNVDA+Shift+X : Ouvrir le menu contextuel xPlorer\nNVDA+Shift+Z Une pression : Annoncer la taille\nNVDA+Shift+Z Deux pressions : Compresser en Zip\nNVDA+Shift+C Une pression : Copier les noms des fichiers et dossiers sélectionnés\nNVDA+Shift+C Deux pressions : Copier la barre d'adresse du dossier actuel\nNVDA+Shift+V Une pression : Copier le contenu\nNVDA+Shift+V Deux pressions : Inverser la sélection\nNVDA+Shift+F2 : Renommer le fichier uniquement"
		},
		{
			"language": "ru",
			"displayName": "xPlorer",
			"description": "Улучшение доступа к Проводнику Windows.\nГорячие клавиши:\nNVDA+Shift+X : Открыть контекстное меню xPlorer\nNVDA+Shift+Z Одно нажатие : Озвучить размер\nNVDA+Shift+Z Два нажатия : Сжать в Zip\nNVDA+Shift+C Одно нажатие : Копировать имена выбранных файлов и папок\nNVDA+Shift+C Два нажатия : Копировать путь из адресной строки текущей папки\nNVDA+Shift+V Одно нажатие : Копировать содержимое\nNVDA+Shift+V Два нажатия : Инвертировать выделение\nNVDA+Shift+F2 : Переименовать только файл"
		}
	]
}

=== nvaccess/addon-datastore/addons/leanCalendar/0.2.3.json
{
	"addonId": "leanCalendar",
	"displayName": "leanCalendar",
	"URL": "https://github.com/cary-rowen/leanCalendar/releases/download/v0.2.3/leanCalendar-0.2.3.nvda-addon",
	"description": "Reports Chinese lunar date, solar terms, Gregorian date and time details, and an interactive calendar query dialog.",
	"sha256": "2e370a5e8e0cf5736c0cdfa271a7d1bad02bdf56e03a5333563af3d2cab66f44",
	"addonVersionName": "0.2.3",
	"addonVersionNumber": {
		"major": 0,
		"minor": 2,
		"patch": 3
	},
	"minNVDAVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Cary-rowen <manchen_0528@outlook.com>",
	"sourceURL": "https://github.com/cary-rowen/leanCalendar",
	"license": "GPL v2",
	"homepage": "https://github.com/cary-rowen/leanCalendar",
	"changelog": "### 0.2.3\n\n* Dependent Updates.",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1782011377000,
	"translations": [
		{
			"language": "zh",
			"displayName": "简易万年历",
			"description": "读出农历日期、节气、公历日期和时间详情，并提供可交互的万年历查询对话框。",
			"changelog": "### 0.2.3\n\n* Dependent Updates."
		}
	]
}

=== nvaccess/addon-datastore/addons/timezone/3.2.0.json
{
	"addonId": "timezone",
	"displayName": "Time Zoner",
	"URL": "https://github.com/munawarb/NVDA-Time-Zoner/releases/download/v3.02/timezone-3.02.nvda-addon",
	"description": "Announces the time and date in selected timezones. Use the Settings dialog to set timezones you want to hear. After you do this, press NVDA+ALT+UP/DOWN ARROW to cycle through your timezone ring and hear times in your selected timezones.",
	"sha256": "83df8d9e50e299cc9a11edd8b7531f82b5b7f222c45cfb7f0087c55c7e9023a6",
	"addonVersionName": "3.02",
	"addonVersionNumber": {
		"major": 3,
		"minor": 2,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2021,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2023,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Munawar Bijani",
	"sourceURL": "https://github.com/munawarb/NVDA-Time-Zoner",
	"license": "GPL v2",
	"homepage": "https://github.com/munawarb/NVDA-Time-Zoner",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": [
		{
			"language": "en",
			"displayName": "Time Zoner",
			"description": "Announces the time and date in selected timezones. Use the Settings dialog to set timezones you want to hear. After you do this, press NVDA+ALT+UP/DOWN ARROW to cycle through your timezone ring and hear times in your selected timezones."
		},
		{
			"language": "pt_BR",
			"displayName": "An\u00fancio de horas em diferentes fusos hor\u00e1rios",
			"description": "Announces the time and date in selected timezones. Use the Settings dialog to set timezones you want to hear. After you do this, press NVDA+ALT+UP/DOWN ARROW to cycle through your timezone ring and hear times in your selected timezones."
		},
		{
			"language": "pt_PT",
			"displayName": "An\u00fancio de horas em diferentes fusos hor\u00e1rios",
			"description": "Announces the time and date in selected timezones. Use the Settings dialog to set timezones you want to hear. After you do this, press NVDA+ALT+UP/DOWN ARROW to cycle through your timezone ring and hear times in your selected timezones."
		}
	]
}
