=== nvaccess/addon-datastore/validation/_validate/addonVersion_schema.json
{
	"examples": [
		{
			"addonId": "easyAddonTech.XYZ",
			"addonVersionNumber": {
				"major": 21,
				"minor": 6,
				"patch": 0
			},
			"addonVersionName": "21.6.0",
			"displayName": "My addon",
			"publisher": "easyAddonTech",
			"description": "Makes doing XYZ easier",
			"homepage": "https://github.com/nvaccess/addon-datastore",
			"minNVDAVersion": {
				"major": 2019,
				"minor": 3,
				"patch": 0
			},
			"lastTestedVersion": {
				"major": 2020,
				"minor": 4,
				"patch": 0
			},
			"channel": "beta",
			"URL": "https://github.com/nvaccess/addon-datastore/releases/download/v0.1.0/myAddon.nvda-addon",
			"sha256": "69D84CA8899800A5575CE31798293CD4FEBAB1D734A07C2E51E56A28E0DF8C82",
			"sourceURL": "https://github.com/nvaccess/addon-datastore/",
			"license": "GPL v2",
			"licenseURL": "https://github.com/nvaccess/addon-datastore/license.MD",
			"changelog": "New features",
			"translations": [
				{
					"language": "de",
					"displayName": "Mein Addon",
					"description": "erleichtert das Durchführen von xyz",
					"changelog": "Neue Funktionen"
				}
			],
			"reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/1942#discussioncomment-7453248",
			"submissionTime": 1723523492363
		}
	],
	"title": "Root",
	"type": "object",
	"description": "Information about an addon release",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"required": [
		"addonId",
		"addonVersionNumber",
		"addonVersionName",
		"displayName",
		"publisher",
		"description",
		"minNVDAVersion",
		"lastTestedVersion",
		"channel",
		"URL",
		"sha256",
		"sourceURL",
		"license",
		"translations"
	],
	"properties": {
		"addonId": {
			"default": "",
			"description": "The ID for the addon, matches the name field in the addon manifest and the folder name for the submission.",
			"examples": [
				"easyAddonTech.XYZ"
			],
			"title": "The ID for the addon",
			"type": "string"
		},
		"addonVersionNumber": {
			"$ref": "#/$defs/canonicalVersion",
			"title": "The addon version number",
			"description": "Pure numerical representation of the version being released.",
			"default": {},
			"type": "object",
			"examples": [
				{
					"major": 21,
					"minor": 6,
					"patch": 0
				}
			]
		},
		"addonVersionName": {
			"title": "The addon version name",
			"description": "The addon version being released. Must match the version in the addon manifest and the file name for the submission.",
			"type": "string",
			"default": "",
			"examples": [
				"21.6.0",
				"21.6",
				"21.06"
			]
		},
		"displayName": {
			"default": "",
			"description": "The name that will be displayed in English for the addon.",
			"examples": [
				"My addon"
			],
			"title": "The display name (en) of the addon",
			"type": "string"
		},
		"publisher": {
			"default": "",
			"description": "The name of the individual, group, or company responsible for the addon.",
			"examples": [
				"NV Access"
			],
			"title": "The publisher name for the addon",
			"type": "string"
		},
		"description": {
			"default": "",
			"description": "The English description of the addon that will be displayed for the addon.",
			"examples": [
				"Makes doing XYZ easier"
			],
			"title": "The description (en) of the addon",
			"type": "string"
		},
		"homepage": {
			"default": "",
			"description": "If the addon has a homepage where users can get more information about the addon, you can specify it here.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore"
			],
			"pattern": "^https:.*",
			"title": "The homepage URL for the addon.",
			"type": "string"
		},
		"minNVDAVersion": {
			"$ref": "#/$defs/canonicalVersion",
			"default": {},
			"title": "The minNVDAVersion schema",
			"description": "The addon will not work with versions of NVDA prior to this version.",
			"examples": [
				{
					"major": 2019,
					"minor": 3,
					"patch": 0
				}
			]
		},
		"lastTestedVersion": {
			"$ref": "#/$defs/canonicalVersion",
			"title": "The lastTestedVersion schema",
			"description": "The add-on has been tested up to and including this version of NVDA",
			"default": {},
			"examples": [
				{
					"major": 2020,
					"minor": 4,
					"patch": 0
				}
			]
		},
		"channel": {
			"default": "",
			"description": "Used to define pre-release (beta) add-ons. Should be either 'stable', 'beta' or 'dev'",
			"examples": [
				"beta"
			],
			"title": "The channel for the addon",
			"enum": [
				"stable",
				"beta",
				"dev"
			],
			"type": "string"
		},
		"URL": {
			"default": "",
			"description": "To allow directly downloading the *.nvda-addon file. The URL should remain valid indefinitely. GitHub release URLs are recommended.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/releases/download/v0.1.0/myAddon.nvda-addon"
			],
			"title": "The URL to download the add-on.",
			"type": "string"
		},
		"sha256": {
			"default": "",
			"description": "Use the python script '_tools/genSha256.py' to generate this value.",
			"examples": [
				"69D84CA8899800A5575CE31798293CD4FEBAB1D734A07C2E51E56A28E0DF8C82"
			],
			"title": "The sha256 for the *.nvda-addon file.",
			"type": "string"
		},
		"sourceURL": {
			"default": "",
			"description": "Allows reviewers to inspect the source code for common issues.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/"
			],
			"title": "The URL for the add-on source",
			"type": "string"
		},
		"license": {
			"default": "",
			"description": "The short name of the license.",
			"examples": [
				"GPL v2"
			],
			"title": "The short name of the license for the addon",
			"type": "string"
		},
		"licenseURL": {
			"default": "",
			"description": "A URL to the full license for the addon.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/license.MD"
			],
			"title": "The URL of the license",
			"type": "string"
		},
		"changelog": {
			"default": "",
			"description": "Changes between the previous and the current version",
			"examples": [
				"New feature"
			],
			"title": "Add-on changelog (en)",
			"type": "string"
		},
		"legacy": {
			"default": false,
			"description": "Legacy add-ons have invalid data or manifest. Legacy add-ons are not listed in the NVDA add-on store.",
			"examples": [
				true
			],
			"title": "Mark add-on as legacy",
			"type": "boolean"
		},
		"translations": {
			"default": [],
			"description": "A collection of translations generated from localized add-on manifests",
			"examples": [
				[
					{
						"language": "de",
						"displayName": "Mein Addon",
						"description": "erleichtert das Durchführen von xyz",
						"changelog": "Neue Funktionen"
					}
				]
			],
			"title": "Translations",
			"type": "array",
			"items": {
				"$ref": "#/$defs/translation"
			}
		},
		"reviewUrl": {
			"default": "",
			"description": "A URL to the discussion comment to review the add-on version.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/discussions/1942#discussioncomment-7453248"
			],
			"title": "Discussion comment URL",
			"type": "string"
		},
		"submissionTime": {
			"default": 0,
			"description": "Timestamp in milliseconds, corresponding to the submission time of the add-on",
			"examples": [
				1723523492363
			],
			"title": "Submission time",
			"type": "number"
		},
		"vtScanUrl": {
			"default": "",
			"description": "A URL to the Virus Total scan for the add-on version.",
			"examples": [
				"https://www.virustotal.com/gui/file/3fda88d598e9747b2dfadfdfb8930a737c0049e9782392bffcd59ef668821547"
			],
			"title": "VirusTotal scan URL",
			"type": "string"
		},
		"scanResults": {
			"default": {},
		"description": "Results from VirusTotal scanning.",
			"examples": [
				{
					"virusTotal": {}
				}
			],
			"title": "Scan results",
			"type": "object"
		}
	},
	"$defs": {
		"canonicalVersion": {
			"default": {},
			"type": "object",
			"examples": [
				{
					"major": 21,
					"minor": 6,
					"patch": 0
				}
			],
			"required": [
				"major",
				"minor",
				"patch"
			],
			"properties": {
				"major": {
					"default": 0,
					"description": "'major' in major.minor.patch",
					"examples": [
						21,
						2019,
						2021
					],
					"title": "The 'major' part of the version number.",
					"type": "integer"
				},
				"minor": {
					"default": 0,
					"description": "The 'minor' part in major.minor.patch",
					"examples": [
						3
					],
					"title": "The 'minor' part of the version number.",
					"type": "integer"
				},
				"patch": {
					"default": 0,
					"description": "The 'patch' part in major.minor.patch",
					"examples": [
						0
					],
					"title": "The 'patch' part of the version number.",
					"type": "integer"
				}
			}
		},
		"translation": {
			"default": {},
			"type": "object",
			"examples": [
				{
					"language": "de",
					"displayName": "Mein Addon",
					"description": "erleichtert das Durchführen von xyz",
					"changelog": "Neue Funktionen"
				}
			],
			"required": [
				"language",
				"displayName",
				"description"
			],
			"properties": {
				"language": {
					"default": "",
					"description": "Language code supported by NVDA",
					"examples": [
						"de",
						"pt_BR"
					],
					"title": "Language code",
					"type": "string"
				},
				"displayName": {
					"default": "",
					"description": "The translated name that will be displayed for the addon.",
					"examples": [
						"Mein Addon"
					],
					"title": "Translated display name",
					"type": "string"
				},
				"description": {
					"default": "",
					"description": "Translated description that will be displayed for the addon.",
					"examples": [
						"erleichtert das Durchführen von xyz"
					],
					"title": "The translated description",
					"type": "string"
				},
				"changelog": {
					"default": "",
					"description": "Translated description of changes between the previous and this add-on version",
					"examples": [
						"Neue Funktionen"
					],
					"title": "The translated changelog",
					"type": "string"
				}
			}
		}
	}
}

=== nvaccess/addon-datastore/addons/My Calculator/1.0.0.json
{
	"addonId": "My Calculator",
	"displayName": "Calculator",
	"URL": "https://github.com/AndhiMardianto/MyCalculator/releases/download/v1.0.0/MyCalculator-1.0.0.nvda-addon",
	"description": "This is a calculator for NVDA addon with better user experience ",
	"sha256": "9a12b0968891955afc3a005a9b9d33a3abcbf6595a0a6ac51963b566d31da76e",
	"addonVersionName": "1.0.0",
	"addonVersionNumber": {
		"major": 1,
		"minor": 0,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2023,
		"minor": 3,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2024,
		"minor": 4,
		"patch": 1
	},
	"channel": "stable",
	"publisher": "Andhi Mardianto",
	"sourceURL": "https://github.com/AndhiMardianto/MyCalculator",
	"license": "GPL v2",
	"homepage": "https://github.com/AndhiMardianto/MyCalculator",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1734718465000,
	"translations": []
}

=== nvaccess/addon-datastore/addons/quickNotetaker/1.2.0.json
{
  "addonId": "quickNotetaker",
  "displayName": "Quick Notetaker",
  "URL": "https://github.com/mohammad-suliman/quickNotetaker/releases/download/v1.2/quickNotetaker-1.2.nvda-addon",
  "description": "A note taker for NVDA. Allows the user to create, edit, view, manage and export notes to different formats.",
  "sha256": "750c8bf59883a67eebbf2988e2c31357512581c40ef810c55a194702ef2da406",
  "addonVersionName": "1.2",
  "addonVersionNumber": {
    "major": 1,
    "minor": 2,
    "patch": 0
  },
  "minNVDAVersion": {
    "major": 2019,
    "minor": 3,
    "patch": 0
  },
  "lastTestedVersion": {
    "major": 2023,
    "minor": 1,
    "patch": 0
  },
  "channel": "stable",
  "publisher": "Mohammad Suliman & Eilana Benish",
  "sourceURL": "https://github.com/mohammad-suliman/quickNotetaker",
  "license": "GPL v2",
  "licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
  "translations": [
    {
      "language": "ar",
      "displayName": "Quick Notetaker",
      "description": "\u0645\u062f\u0648\u0646 \u0645\u0644\u0627\u062d\u0638\u0627\u062a \u0644 NVDA. \u064a\u0645\u0643\u0646 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645 \u0645\u0646 \u0625\u0646\u0634\u0627\u0621\u060c \u062a\u062d\u0631\u064a\u0631\u060c \u0639\u0631\u0636\u060c \u0625\u062f\u0627\u0631\u0629 \u0648\u062a\u0635\u062f\u064a\u0631 \u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0627\u062a \u0627\u0644\u0649 \u0635\u064a\u063a \u0645\u062e\u062a\u0644\u0641\u0629."
    },
    {
      "language": "de",
      "displayName": "Quick Notetaker",
      "description": "Ein Notizbuch f\u00fcr NVDA. Erm\u00f6glicht dem Benutzer das Erstellen, Bearbeiten, Anzeigen, Verwalten und Exportieren von Notizen."
    },
    {
      "language": "he",
      "displayName": "Quick Notetaker",
      "description": "\u05e2\u05d5\u05e8\u05da \u05d4\u05e4\u05ea\u05e7\u05d9\u05dd \u05dc NVDA. \u05de\u05d0\u05e4\u05e9\u05e8 \u05d9\u05e6\u05d9\u05e8\u05d4, \u05e2\u05e8\u05d9\u05db\u05d4, \u05e6\u05e4\u05d9\u05d9\u05d4, \u05e0\u05d9\u05d4\u05d5\u05dc \u05d5\u05d9\u05e6\u05d5\u05d0 \u05d4\u05d4\u05e2\u05e8\u05d5\u05ea \u05dc\u05e4\u05d5\u05e8\u05de\u05d8\u05d9\u05dd \u05e9\u05d5\u05e0\u05d9\u05dd."
    },
    {
      "language": "ru",
      "displayName": "\u0411\u044b\u0441\u0442\u0440\u044b\u0439 \u0431\u043b\u043e\u043a\u043d\u043e\u0442",
      "description": "\u0411\u043b\u043e\u043a\u043d\u043e\u0442 \u0434\u043b\u044f NVDA. \u041f\u043e\u0437\u0432\u043e\u043b\u044f\u0435\u0442 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044e \u0441\u043e\u0437\u0434\u0430\u0432\u0430\u0442\u044c, \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c, \u043f\u0440\u043e\u0441\u043c\u0430\u0442\u0440\u0438\u0432\u0430\u0442\u044c, \u0443\u043f\u0440\u0430\u0432\u043b\u044f\u0442\u044c \u0438 \u044d\u043a\u0441\u043f\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u0437\u0430\u043c\u0435\u0442\u043a\u0438 \u0432 \u0440\u0430\u0437\u043b\u0438\u0447\u043d\u044b\u0435 \u0444\u043e\u0440\u043c\u0430\u0442\u044b."
    },
    {
      "language": "zh_CN",
      "displayName": "\u5feb\u6377\u7b14\u8bb0",
      "description": "\u7528\u4e8e NVDA \u7684\u5feb\u6377\u7b14\u8bb0\u63d2\u4ef6\u3002\u8be5\u63d2\u4ef6\u53ef\u4ee5\u8ba9\u7528\u6237\u521b\u5efa\u3001\u7f16\u8f91\u3001\u67e5\u770b\u3001\u7ba1\u7406\u548c\u5bfc\u51fa\u4e0d\u540c\u683c\u5f0f\u7684\u7b14\u8bb0\u3002"
    }
  ],
  "vtScanUrl": "https://www.virustotal.com/gui/file/750c8bf59883a67eebbf2988e2c31357512581c40ef810c55a194702ef2da406"
}

=== nvaccess/addon-datastore/addons/stationPlaylist/23.5.0.json
{
	"addonId": "stationPlaylist",
	"displayName": "StationPlaylist",
	"URL": "https://github.com/ChrisDuffley/stationPlaylist/releases/download/23.05/stationPlaylist-23.05.nvda-addon",
	"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere.",
	"sha256": "485f6908e7ec230084a19ef946829a568b859993aa165be704a48bdbe6c665d8",
	"addonVersionName": "23.05",
	"addonVersionNumber": {
		"major": 23,
		"minor": 5,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2022,
		"minor": 4,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2023,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "ChrisDuffley",
	"sourceURL": "https://github.com/ChrisDuffley/StationPlaylist",
	"license": "GPL v2",
	"homepage": "https://github.com/ChrisDuffley/stationPlaylist",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": [
		{
			"language": "ar",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "bg",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "de",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "de_CH",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "es",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "es_CO",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "fr",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "gl",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "he",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "hr",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "hu",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "kn",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "ne",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "pl",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "pt_BR",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "pt_PT",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "ro",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "sk",
			"displayName": "Station Playlist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "sr",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "tr",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		},
		{
			"language": "vi",
			"displayName": "StationPlaylist",
			"description": "Enhances support for StationPlaylist apps. In addition, adds global commands for the Studio application from everywhere."
		}
	]
}

=== nvaccess/addon-datastore/addons/eclipseEnhance/2024.1.0.json
{
	"addonId": "eclipseEnhance",
	"displayName": "Eclipse Enhance",
	"URL": "https://github.com/albzan/eclipse-nvda/releases/download/2024.1/eclipseEnhance-2024.1.nvda-addon",
	"description": "Enhance the speech and braille support while using the Eclipse IDE reportings errors and warnings.",
	"sha256": "9afc6e1b72b0d28bcef6993d7f6cf3cddf0ed89c755e6d199a9eceeabcba1979",
	"addonVersionName": "2024.1",
	"addonVersionNumber": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2021,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "albzan",
	"sourceURL": "https://github.com/albzan/eclipse-nvda",
	"license": "GPL v2",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": [
		{
			"language": "es",
			"displayName": "Eclipse Enhance",
			"description": "Mejora el soporte de habla y braille al usar el entorno de desarrollo  integrado Eclipse reportando errores y advertencias."
		}
	]
}

=== nvaccess/addon-datastore/addons/Internet speed checker/1.0.0.json
{
	"addonId": "Internet speed checker",
	"displayName": "Internet Speed Checker",
	"URL": "https://github.com/anhlocvu/Internet-speed-checker/releases/download/v1.0.0/Internet.speed.checker-1.0.0.nvda-addon",
	"description": "An add-on to check your internet speed (download, upload, ping) with NVDA.",
	"sha256": "22340c725b2da2e5e63b0fb88f4244ba49fd6ec528bedbfb5de7a446dd0c868a",
	"addonVersionName": "1.0.0",
	"addonVersionNumber": {
		"major": 1,
		"minor": 0,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2025,
		"minor": 3,
		"patch": 3
	},
	"channel": "stable",
	"publisher": "lc boy",
	"sourceURL": "https://github.com/anhlocvu/Internet-speed-checker",
	"license": "GPL v2",
	"homepage": "https://github.com/anhlocvu/Internet-speed-checker",
	"changelog": "",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1772517583000,
	"translations": []
}

=== nvaccess/addon-datastore/addons/SessionTimer/0.0.4.json
{
	"addonId": "SessionTimer",
	"displayName": "Session Timer",
	"URL": "https://github.com/Accessibility-armenia/nvda-SessionTimer/releases/download/v0.0.4/SessionTimer-0.0.4.nvda-addon",
	"description": "Announces how long NVDA has been running since startup.",
	"sha256": "ef98498b8e65f1e5e6441760fbb8e8cbfb58c506c26a2a3bb3bee41cd56ac0e7",
	"addonVersionName": "0.0.4",
	"addonVersionNumber": {
		"major": 0,
		"minor": 0,
		"patch": 4
	},
	"minNVDAVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 3,
		"patch": 3
	},
	"channel": "stable",
	"publisher": "Tigran Navasardyan",
	"sourceURL": "https://github.com/Accessibility-armenia/nvda-SessionTimer",
	"license": "GPL v2",
	"homepage": "https://github.com/Accessibility-armenia/nvda-SessionTimer",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1775108017000,
	"translations": []
}

=== nvaccess/addon-datastore/addons/radioCenter/1.5.2.json
{
  "addonId": "radioCenter",
  "displayName": "radioCenter",
  "URL": "https://github.com/DollaR84/radioCenter/releases/download/stable/radioCenter-1.5.2.nvda-addon",
  "description": "this addon allows you to play online radio stations",
  "sha256": "e915da26d7effbcbce1c924e96ed21a7309046c6d096bc82e2fcef859c527b19",
  "addonVersionName": "1.5.2",
  "addonVersionNumber": {
    "major": 1,
    "minor": 5,
    "patch": 2
  },
  "minNVDAVersion": {
    "major": 2021,
    "minor": 2,
    "patch": 0
  },
  "lastTestedVersion": {
    "major": 2024,
    "minor": 1,
    "patch": 0
  },
  "channel": "stable",
  "publisher": "Ruslan Dolovaniuk",
  "sourceURL": "https://github.com/DollaR84/radioCenter",
  "license": "GPL v2",
  "homepage": "https://github.com/DollaR84/radioCenter",
  "licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
  "translations": [
    {
      "language": "cz",
      "displayName": "radioCenter",
      "description": "tento addon v\u00e1m umo\u017e\u0148uje poslouchat online rozhlasov\u00e9 stanice"
    },
    {
      "language": "en",
      "displayName": "radioCenter",
      "description": "this addon allows you to play online radio stations"
    },
    {
      "language": "ru",
      "displayName": "radioCenter",
      "description": "\u044d\u0442\u043e \u0434\u043e\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u043f\u043e\u0437\u0432\u043e\u043b\u044f\u0435\u0442 \u0432\u0430\u043c \u0441\u043b\u0443\u0448\u0430\u0442\u044c \u043e\u043d\u043b\u0430\u0439\u043d \u0440\u0430\u0434\u0438\u043e\u0441\u0442\u0430\u043d\u0446\u0438\u0438"
    },
    {
      "language": "tr",
      "displayName": "radyo merkezi",
      "description": "bu eklenti \u00e7evrimi\u00e7i radyo istasyonlar\u0131n\u0131 \u00e7alman\u0131za olanak tan\u0131r."
    },
    {
      "language": "uk",
      "displayName": "radioCenter",
      "description": "\u0446\u0435 \u0434\u043e\u043f\u043e\u0432\u043d\u0435\u043d\u043d\u044f \u0434\u043e\u0437\u0432\u043e\u043b\u044f\u0454 \u0432\u0430\u043c \u0441\u043b\u0443\u0445\u0430\u0442\u0438 \u043e\u043d\u043b\u0430\u0439\u043d \u0440\u0430\u0434\u0456\u043e\u0441\u0442\u0430\u043d\u0446\u0456\u0457"
    }
  ],
  "reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/3763"
}

=== nvaccess/addon-datastore/addons/terminalAccess/1.0.45.json
{
	"addonId": "terminalAccess",
	"displayName": "Terminal Access for NVDA",
	"URL": "https://github.com/PratikP1/Terminal-Access-for-NVDA/releases/download/v1.0.45/terminalAccess-1.0.45.nvda-addon",
	"description": "Provides enhanced terminal accessibility for Windows Terminal and PowerShell, enabling screen reader users to efficiently navigate and interact with command-line interfaces. Inspired by TDSR (Terminal Data Structure Reader) and incorporates functionality from both TDSR and Speakup. Advanced features inspired by community suggestions and discussions.",
	"sha256": "0f4e154e7d76066a9e07d51f8c4b2c783deb6e500b0e51100e2e5cb929585dbc",
	"addonVersionName": "1.0.45",
	"addonVersionNumber": {
		"major": 1,
		"minor": 0,
		"patch": 45
	},
	"minNVDAVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Pratik Patel",
	"sourceURL": "https://github.com/PratikP1/Terminal-Access-for-NVDA",
	"license": "GPL v3",
	"homepage": "https://github.com/PratikP1/Terminal-Access-for-NVDA",
	"licenseURL": "https://www.gnu.org/licenses/gpl-3.0.html",
	"submissionTime": 1771861058000,
	"translations": []
}
