=== nvaccess/addon-datastore/validation/_validate/addonVersion_schema.json
{
	"examples": [
		{
			"addonId": "easyAddonTech.XYZ",
			"addonVersionNumber": {
				"major": 21,
				"minor": 6,
				"patch": 0
			},
			"addonVersionName": "21.6.0",
			"displayName": "My addon",
			"publisher": "easyAddonTech",
			"description": "Makes doing XYZ easier",
			"homepage": "https://github.com/nvaccess/addon-datastore",
			"minNVDAVersion": {
				"major": 2019,
				"minor": 3,
				"patch": 0
			},
			"lastTestedVersion": {
				"major": 2020,
				"minor": 4,
				"patch": 0
			},
			"channel": "beta",
			"URL": "https://github.com/nvaccess/addon-datastore/releases/download/v0.1.0/myAddon.nvda-addon",
			"sha256": "69D84CA8899800A5575CE31798293CD4FEBAB1D734A07C2E51E56A28E0DF8C82",
			"sourceURL": "https://github.com/nvaccess/addon-datastore/",
			"license": "GPL v2",
			"licenseURL": "https://github.com/nvaccess/addon-datastore/license.MD",
			"changelog": "New features",
			"translations": [
				{
					"language": "de",
					"displayName": "Mein Addon",
					"description": "erleichtert das Durchführen von xyz",
					"changelog": "Neue Funktionen"
				}
			],
			"reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/1942#discussioncomment-7453248",
			"submissionTime": 1723523492363
		}
	],
	"title": "Root",
	"type": "object",
	"description": "Information about an addon release",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"required": [
		"addonId",
		"addonVersionNumber",
		"addonVersionName",
		"displayName",
		"publisher",
		"description",
		"minNVDAVersion",
		"lastTestedVersion",
		"channel",
		"URL",
		"sha256",
		"sourceURL",
		"license",
		"translations"
	],
	"properties": {
		"addonId": {
			"default": "",
			"description": "The ID for the addon, matches the name field in the addon manifest and the folder name for the submission.",
			"examples": [
				"easyAddonTech.XYZ"
			],
			"title": "The ID for the addon",
			"type": "string"
		},
		"addonVersionNumber": {
			"$ref": "#/$defs/canonicalVersion",
			"title": "The addon version number",
			"description": "Pure numerical representation of the version being released.",
			"default": {},
			"type": "object",
			"examples": [
				{
					"major": 21,
					"minor": 6,
					"patch": 0
				}
			]
		},
		"addonVersionName": {
			"title": "The addon version name",
			"description": "The addon version being released. Must match the version in the addon manifest and the file name for the submission.",
			"type": "string",
			"default": "",
			"examples": [
				"21.6.0",
				"21.6",
				"21.06"
			]
		},
		"displayName": {
			"default": "",
			"description": "The name that will be displayed in English for the addon.",
			"examples": [
				"My addon"
			],
			"title": "The display name (en) of the addon",
			"type": "string"
		},
		"publisher": {
			"default": "",
			"description": "The name of the individual, group, or company responsible for the addon.",
			"examples": [
				"NV Access"
			],
			"title": "The publisher name for the addon",
			"type": "string"
		},
		"description": {
			"default": "",
			"description": "The English description of the addon that will be displayed for the addon.",
			"examples": [
				"Makes doing XYZ easier"
			],
			"title": "The description (en) of the addon",
			"type": "string"
		},
		"homepage": {
			"default": "",
			"description": "If the addon has a homepage where users can get more information about the addon, you can specify it here.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore"
			],
			"pattern": "^https:.*",
			"title": "The homepage URL for the addon.",
			"type": "string"
		},
		"minNVDAVersion": {
			"$ref": "#/$defs/canonicalVersion",
			"default": {},
			"title": "The minNVDAVersion schema",
			"description": "The addon will not work with versions of NVDA prior to this version.",
			"examples": [
				{
					"major": 2019,
					"minor": 3,
					"patch": 0
				}
			]
		},
		"lastTestedVersion": {
			"$ref": "#/$defs/canonicalVersion",
			"title": "The lastTestedVersion schema",
			"description": "The add-on has been tested up to and including this version of NVDA",
			"default": {},
			"examples": [
				{
					"major": 2020,
					"minor": 4,
					"patch": 0
				}
			]
		},
		"channel": {
			"default": "",
			"description": "Used to define pre-release (beta) add-ons. Should be either 'stable', 'beta' or 'dev'",
			"examples": [
				"beta"
			],
			"title": "The channel for the addon",
			"enum": [
				"stable",
				"beta",
				"dev"
			],
			"type": "string"
		},
		"URL": {
			"default": "",
			"description": "To allow directly downloading the *.nvda-addon file. The URL should remain valid indefinitely. GitHub release URLs are recommended.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/releases/download/v0.1.0/myAddon.nvda-addon"
			],
			"title": "The URL to download the add-on.",
			"type": "string"
		},
		"sha256": {
			"default": "",
			"description": "Use the python script '_tools/genSha256.py' to generate this value.",
			"examples": [
				"69D84CA8899800A5575CE31798293CD4FEBAB1D734A07C2E51E56A28E0DF8C82"
			],
			"title": "The sha256 for the *.nvda-addon file.",
			"type": "string"
		},
		"sourceURL": {
			"default": "",
			"description": "Allows reviewers to inspect the source code for common issues.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/"
			],
			"title": "The URL for the add-on source",
			"type": "string"
		},
		"license": {
			"default": "",
			"description": "The short name of the license.",
			"examples": [
				"GPL v2"
			],
			"title": "The short name of the license for the addon",
			"type": "string"
		},
		"licenseURL": {
			"default": "",
			"description": "A URL to the full license for the addon.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/license.MD"
			],
			"title": "The URL of the license",
			"type": "string"
		},
		"changelog": {
			"default": "",
			"description": "Changes between the previous and the current version",
			"examples": [
				"New feature"
			],
			"title": "Add-on changelog (en)",
			"type": "string"
		},
		"legacy": {
			"default": false,
			"description": "Legacy add-ons have invalid data or manifest. Legacy add-ons are not listed in the NVDA add-on store.",
			"examples": [
				true
			],
			"title": "Mark add-on as legacy",
			"type": "boolean"
		},
		"translations": {
			"default": [],
			"description": "A collection of translations generated from localized add-on manifests",
			"examples": [
				[
					{
						"language": "de",
						"displayName": "Mein Addon",
						"description": "erleichtert das Durchführen von xyz",
						"changelog": "Neue Funktionen"
					}
				]
			],
			"title": "Translations",
			"type": "array",
			"items": {
				"$ref": "#/$defs/translation"
			}
		},
		"reviewUrl": {
			"default": "",
			"description": "A URL to the discussion comment to review the add-on version.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/discussions/1942#discussioncomment-7453248"
			],
			"title": "Discussion comment URL",
			"type": "string"
		},
		"submissionTime": {
			"default": 0,
			"description": "Timestamp in milliseconds, corresponding to the submission time of the add-on",
			"examples": [
				1723523492363
			],
			"title": "Submission time",
			"type": "number"
		},
		"vtScanUrl": {
			"default": "",
			"description": "A URL to the Virus Total scan for the add-on version.",
			"examples": [
				"https://www.virustotal.com/gui/file/3fda88d598e9747b2dfadfdfb8930a737c0049e9782392bffcd59ef668821547"
			],
			"title": "VirusTotal scan URL",
			"type": "string"
		},
		"scanResults": {
			"default": {},
		"description": "Results from VirusTotal scanning.",
			"examples": [
				{
					"virusTotal": {}
				}
			],
			"title": "Scan results",
			"type": "object"
		}
	},
	"$defs": {
		"canonicalVersion": {
			"default": {},
			"type": "object",
			"examples": [
				{
					"major": 21,
					"minor": 6,
					"patch": 0
				}
			],
			"required": [
				"major",
				"minor",
				"patch"
			],
			"properties": {
				"major": {
					"default": 0,
					"description": "'major' in major.minor.patch",
					"examples": [
						21,
						2019,
						2021
					],
					"title": "The 'major' part of the version number.",
					"type": "integer"
				},
				"minor": {
					"default": 0,
					"description": "The 'minor' part in major.minor.patch",
					"examples": [
						3
					],
					"title": "The 'minor' part of the version number.",
					"type": "integer"
				},
				"patch": {
					"default": 0,
					"description": "The 'patch' part in major.minor.patch",
					"examples": [
						0
					],
					"title": "The 'patch' part of the version number.",
					"type": "integer"
				}
			}
		},
		"translation": {
			"default": {},
			"type": "object",
			"examples": [
				{
					"language": "de",
					"displayName": "Mein Addon",
					"description": "erleichtert das Durchführen von xyz",
					"changelog": "Neue Funktionen"
				}
			],
			"required": [
				"language",
				"displayName",
				"description"
			],
			"properties": {
				"language": {
					"default": "",
					"description": "Language code supported by NVDA",
					"examples": [
						"de",
						"pt_BR"
					],
					"title": "Language code",
					"type": "string"
				},
				"displayName": {
					"default": "",
					"description": "The translated name that will be displayed for the addon.",
					"examples": [
						"Mein Addon"
					],
					"title": "Translated display name",
					"type": "string"
				},
				"description": {
					"default": "",
					"description": "Translated description that will be displayed for the addon.",
					"examples": [
						"erleichtert das Durchführen von xyz"
					],
					"title": "The translated description",
					"type": "string"
				},
				"changelog": {
					"default": "",
					"description": "Translated description of changes between the previous and this add-on version",
					"examples": [
						"Neue Funktionen"
					],
					"title": "The translated changelog",
					"type": "string"
				}
			}
		}
	}
}

=== nvaccess/addon-datastore/addons/Access8Math/4.5.0.json
{
	"addonId": "Access8Math",
	"displayName": "Access8Math",
	"URL": "https://github.com/tsengwoody/Access8Math/releases/download/v4.5/Access8Math-4.5.nvda-addon",
	"description": "Allows access math content written by MathML ; Allows write math content by LaTeX",
	"sha256": "6704f0a11d0057766901b7e94ccb20a16bd2c21169384fdfe5193853dfdd0a7d",
	"addonVersionName": "4.5",
	"addonVersionNumber": {
		"major": 4,
		"minor": 5,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2025,
		"minor": 3,
		"patch": 3
	},
	"channel": "stable",
	"publisher": "Tseng Woody",
	"sourceURL": "https://github.com/tsengwoody/Access8Math",
	"license": "GPL v2",
	"homepage": "https://github.com/tsengwoody/Access8Math",
	"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths.",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1774624588000,
	"translations": [
		{
			"language": "de",
			"displayName": "Access8Math",
			"description": "Ermöglicht es, mathematische Inhalte im MathML-Format zu lesen sowie Math-ML mittels Latex zu erzeugen",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "es",
			"displayName": "Access8Math",
			"description": "Permite acceder a contenido matemático escrito en MathML; permite escribir contenido matemático en LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "fr",
			"displayName": "Access8Math",
			"description": "Permet l'accès au contenu mathématique écrit en MathML ; Permet d'écrire du contenu mathématique en LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "gl",
			"displayName": "Access8Math",
			"description": "Permite acesar a contido matemático escrebido en MathML; permite escrebir contido matemático en LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "it",
			"displayName": "Access8Math",
			"description": "Consente di accedere a contenuti matematici scritti con MathML; Consente di scrivere contenuti matematici con LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "pt_BR",
			"displayName": "Access8Math",
			"description": "Permite acessar conteúdo matemático escrito com MathML; Permite escrever conteúdo matemático através de LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "pt_PT",
			"displayName": "Access8Math",
			"description": "Permite aceder a conteúdos matemáticos escritos em MathML; Permite escrever conteúdos matemáticos em LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "ro",
			"displayName": "Access8Math",
			"description": "Permite accesul la conținut matematic scris de MathML; Permite scrierea conținutului matematic prin LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "ru",
			"displayName": "Access8Math",
			"description": "Предоставляет доступ к математическим выражениям, написанным на MathML; позволяет записывать математические выражения с помощью LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "tr",
			"displayName": "Access8Math",
			"description": "MathML ile yazılan matematik içeriğine erişime sağlar ve LaTeX ile matematik içeriği oluşturmaya izin verir",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "zh_CN",
			"displayName": "Access8Math",
			"description": "可以閱讀 MathML 編寫的數學內容；可以使用 LaTeX 書寫數學內容",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "zh_TW",
			"displayName": "Access8Math",
			"description": "允許閱讀 MathML 編寫的數學內容；允許通過 LaTeX 書寫數學內容",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		}
	]
}

=== nvaccess/addon-datastore/addons/screenWrapping/2.2.0.json
{
  "addonId": "screenWrapping",
  "displayName": "screen wrapping for nvda",
  "URL": "https://github.com/hamadatrichine/nvda-screen-wrapping/releases/download/V2.2.0/screenWrapping-2.2.0.nvda-addon",
  "description": "This addon brings the screen wrapping feature to nvda.\n\tWhen you press quick navigation keys such as h, b, f and others, you will be placed on the next element regardless of your current position on a webpage.\n\tIf elements are not found below your position, you will be placed at the first element of the requested type available from the beginning of the page and vice versa when you are searching upwards. this also extends to the find dialog of nvda.",
  "sha256": "5b94e3d7c621aea78bc15404ead107e25d553b961a6ba662b0a28e1f9438ce5f",
  "addonVersionName": "2.2.0",
  "addonVersionNumber": {
    "major": 2,
    "minor": 2,
    "patch": 0
  },
  "minNVDAVersion": {
    "major": 2024,
    "minor": 2,
    "patch": 0
  },
  "lastTestedVersion": {
    "major": 2024,
    "minor": 2,
    "patch": 0
  },
  "channel": "stable",
  "publisher": "Hamada TRICHINE",
  "sourceURL": "https://github.com/hamadatrichine/nvda-screen-wrapping",
  "license": "GPL v2",
  "homepage": "https://github.com/hamadatrichine/nvda-screen-wrapping",
  "licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
  "translations": [
    {
      "language": "pt_BR",
      "displayName": "Loop de tela para NVDA",
      "description": "This addon brings the screen wrapping feature to nvda.\n\tWhen you press quick navigation keys such as h, b, f and others, you will be placed on the next element regardless of your current position on a webpage.\n\tIf elements are not found below your position, you will be placed at the first element of the requested type available from the beginning of the page and vice versa when you are searching upwards. this also extends to the find dialog of nvda."
    },
    {
      "language": "pt_PT",
      "displayName": "loop de ecr\u00e3 para NVDA",
      "description": "Este extra tr\u00e1s o loop de ecran para o NVDA.\nQuando pressiona as teclas de navega\u00e7\u00e3o r\u00e1pida, tais como h, b, f ou outras, ser\u00e1 posicionado no pr\u00f3ximo elemento do tipo solicitado independentemente da posi\u00e7\u00e3o actual em que est\u00e1 no texto.\nSe o elemento sollicitado n\u00e3o for encontrado abaixo da posi\u00e7\u00e3o actual, ser\u00e1 posicionado no primeiro elemento do tipo solicitado no texto. O inverso acontece se estiver a procurar por elementos na ordem reversa."
    },
    {
      "language": "ru",
      "displayName": "screen wrapping for nvda",
      "description": "This addon brings the screen wrapping feature to nvda.\n\tWhen you press quick navigation keys such as h, b, f and others, you will be placed on the next element regardless of your current position on a webpage.\n\tIf elements are not found below your position, you will be placed at the first element of the requested type available from the beginning of the page and vice versa when you are searching upwards. this also extends to the find dialog of nvda."
    },
    {
      "language": "zh_CN",
      "displayName": "\u5faa\u73af\u6d4f\u89c8\u6a21\u5f0f",
      "description": "\u8fd9\u4e2a\u63d2\u4ef6\u4e3a nvda \u589e\u52a0\u4e86\u5faa\u73af\u6d4f\u89c8\u529f\u80fd\u3002\n\u5728\u60a8\u4f7f\u7528\u5355\u952e\u5bfc\u822a\u5982 h\u3001b\u3001f \u8fc7\u7a0b\u4e2d\uff0c\u4f1a\u5411\u4e0b\u8df3\u8f6c\u76f8\u5e94\u7684\u5143\u7d20\u3002\n\u5982\u679c\u5f80\u4e0b\u627e\u4e0d\u5230\u5143\u7d20\uff0c\u5219\u4f1a\u4ece\u5934\u5f00\u59cb\u7ee7\u7eed\u6309\u76f8\u5e94\u5143\u7d20\u7c7b\u578b\u8df3\u8f6c\uff0c\u53cd\u4e4b\u4ea6\u7136\uff0c\u5411\u4e0a\u8df3\u8f6c\u4e5f\u662f\u5982\u6b64\u3002\n\u5f53\u7136\uff0c\u8be5\u529f\u80fd\u5bf9\u4e8e NVDA \u7684\u67e5\u627e\u529f\u80fd\u4e5f\u8bd5\u7528\u3002"
    }
  ],
  "reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/3282"
}

=== nvaccess/addon-datastore/addons/SimpleCalculator/1.0.0.json
{
	"addonId": "SimpleCalculator",
	"displayName": "Simple calculator",
	"URL": "https://github.com/mesteranas/SimpleCalculator/releases/download/v1.0/SimpleCalculator.nvda-addon",
	"description": "A simple add-on for NVDA to make Arithmetical operations.\nUse the add-on\nPress NVDA+ALT+S to open the add-on window",
	"sha256": "1d30ef429fd949fbe157abf95595412a118336001c2fb1480f7ec74e369c004d",
	"addonVersionName": "1.0",
	"addonVersionNumber": {
		"major": 1,
		"minor": 0,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2019,
		"minor": 3,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "mesteranas",
	"sourceURL": "https://github.com/mesteranas/SimpleCalculator/",
	"license": "GPL v2",
	"homepage": "https://github.com/mesteranas/SimpleCalculator",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": []
}

=== nvaccess/addon-datastore/addons/Rutas_fav/1.0.2.json
{
	"addonId": "Rutas_fav",
	"displayName": "Rutas favoritas",
	"URL": "https://github.com/Reyes2005/rutas_fav/releases/download/v1.0.2/Rutas_fav-1.0.2.nvda-addon",
	"description": "Este addon tiene como finalidad el tener una gesti\u00f3n simple pero eficaz de rutas favoritas para as\u00ed, en determinados casos, abrir estas rutas r\u00e1pidamente",
	"sha256": "3289faf85de609812184b897899336e3831c92cdf2d90dc5af856dd9eafbdbe6",
	"addonVersionName": "1.0.2",
	"addonVersionNumber": {
		"major": 1,
		"minor": 0,
		"patch": 2
	},
	"minNVDAVersion": {
		"major": 2023,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "\u00c1ngel Reyes",
	"sourceURL": "https://github.com/reyes2005/rutas_fav/",
	"license": "GPL v2",
	"homepage": "https://github.com/reyes2005/rutas_fav/",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": [
		{
			"language": "en",
			"displayName": "Rutas favoritas",
			"description": "The purpose of this addon is to have a simple but effective management of favorite paths in order to, in certain cases, open these paths quickly."
		}
	]
}

=== nvaccess/addon-datastore/addons/deltaTalk/0.4.1.json
{
	"addonId": "deltaTalk",
	"displayName": "MicroPower DeltaTalk TTS",
	"URL": "https://github.com/wendrillaksenow/deltaTalkTTS/releases/download/0.4.1/deltaTalk-0.4.1.nvda-addon",
	"description": "DeltaTalk is the first high-quality speech synthesizer available for the Portuguese language.\nThis add-on implements NVDA compatibility with this synthesizer.",
	"sha256": "c194cf29e4f35bd99a6c446f7dd0dc8ca92748fbc3233266b0e51b0c4b017d21",
	"addonVersionName": "0.4.1",
	"addonVersionNumber": {
		"major": 0,
		"minor": 4,
		"patch": 1
	},
	"minNVDAVersion": {
		"major": 2023,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Patrick Barboza <patrickbarboza774@gmail.com>, Wendrill Aksenow Brandão <wendrillaksenow@gmail.com>",
	"sourceURL": "https://github.com/wendrillaksenow/deltaTalkTTS",
	"license": "GPL v2",
	"homepage": "https://github.com/wendrillaksenow/deltaTalkTTS",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1755264186000,
	"translations": [
		{
			"language": "pt_BR",
			"displayName": "MicroPower DeltaTalk TTS",
			"description": "DeltaTalk é o primeiro sintetizador de voz de alta qualidade, disponível para a língua portuguesa.\nEste complemento implementa a compatibilidade do NVDA com este sintetizador."
		},
		{
			"language": "pt_PT",
			"displayName": "MicroPower DeltaTalk TTS",
			"description": "O DeltaTalk é o primeiro sintetizador de fala de alta qualidade, disponível para a língua portuguesa.\nEste extra implementa a compatibilidade do NVDA com este sintetizador."
		}
	],
	"vtScanUrl": "https://www.virustotal.com/gui/file/c194cf29e4f35bd99a6c446f7dd0dc8ca92748fbc3233266b0e51b0c4b017d21"
}

=== nvaccess/addon-datastore/addons/wordNav/2.1.0.json
{
	"addonId": "wordNav",
	"displayName": "WordNav",
	"URL": "https://github.com/mltony/nvda-word-nav/releases/download/v2.1/wordNav-2.1.nvda-addon",
	"description": "Improved navigate by word and word selection commands.",
	"sha256": "d698428a14a21ba2617a4c4d65c6b8c9e3e41305cff05c45eb5c3625b8fff8c4",
	"addonVersionName": "2.1",
	"addonVersionNumber": {
		"major": 2,
		"minor": 1,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 2,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2024,
		"minor": 2,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Tony Malykh",
	"sourceURL": "https://github.com/mltony/nvda-word-nav/",
	"license": "GPL v2",
	"homepage": "https://github.com/mltony/nvda-word-nav/releases",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": [
		{
			"language": "es",
			"displayName": "WordNav",
			"description": "Mejora las \u00f3rdenes de navegaci\u00f3n por palabras y selecci\u00f3n de las mismas."
		},
		{
			"language": "fi",
			"displayName": "Sananavigointi",
			"description": "Parannellut sananavigointi- ja sananvalintakomennot."
		},
		{
			"language": "fr",
			"displayName": "WordNav",
			"description": "Am\u00e9lioration de la navigation par mot et commandes de s\u00e9lection de mots."
		},
		{
			"language": "hr",
			"displayName": "Kretanje po rije\u010dima (WordNav)",
			"description": "Pobolj\u0161ano kretanje po rije\u010dima i pre\u010daci za izbor rije\u010di."
		},
		{
			"language": "pt_PT",
			"displayName": "WordNav",
			"description": "Melhoria dos comandos de navega\u00e7\u00e3o por palavra e de sele\u00e7\u00e3o de palavras."
		},
		{
			"language": "tr",
			"displayName": "Kelime Dola\u015f\u0131m\u0131",
			"description": "Kelimeye g\u00f6re dola\u015fma ve kelime se\u00e7me komutlar\u0131 geli\u015ftirildi."
		},
		{
			"language": "uk",
			"displayName": "\u041d\u0430\u0432\u0456\u0433\u0430\u0446\u0456\u044f \u043f\u043e \u0441\u043b\u043e\u0432\u0430\u0445",
			"description": "Improved navigate by word and word selection commands."
		},
		{
			"language": "zh_CN",
			"displayName": "\u5355\u8bcd\u5bfc\u822a",
			"description": "\u6539\u8fdb\u4e86\u7528\u4e8e\u5355\u8bcd\u5bfc\u822a\u548c\u5355\u8bcd\u9009\u62e9\u7684\u547d\u4ee4\u3002"
		}
	]
}
